name: 02-run-after-another

on:
  workflow_run:
    workflows: [01-run-on-push]
    types: [completed]

jobs:
  if-pr:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.event == 'pull_request') && (github.event.workflow_run.conclusion == 'success') }}
    steps:
      - run: echo 'The triggering workflow has passed and was triggered via a pull_request'
  if-push:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.event == 'push') && (github.event.workflow_run.conclusion == 'success') }}
    steps:
      - run: echo 'The triggering workflow has passed and was triggered via a push'
  run-after-another:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Test step for PR
        run: echo "No op step added just for testing"
