name: 05-download-artifacts
run-name: Triggered via ${{ github.event.workflow_run.name }}#${{ github.event.workflow_run.run_number }}(${{ github.event.workflow_run.id }}) for a ${{ github.event.workflow_run.event }} event

on:
  workflow_run:
    workflows: [04-upload-artifacts]
    types: [completed]

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/download-artifact@v4
        with:
          name: demo-artifact
          path: path/to/artifact
          run-id: ${{ github.event.workflow_run.id }}
      - name: Display structure of downloaded files
        run: ls -R path/to/artifact
